/***************************************************************************
 * Copyright (c) 2025-2026 Dmytro Ostapenko. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * *************************************************************************/

export const lat = {
    appTitle: "Legentia",
    errorAIFeaturesDisabled: "Functiones AI sunt deactivatae. Quaeso primum clavem API constitue.",
    errorTranslationNotAvailable: "Versio nunc non est praesto.",
    voiceModelName: "", // "Latin Male" for latin language
    infoWordAddedToPracticeList: "Verbum ad indicem exercitationis additum est.",
    infoWordRemovedFromPracticeList: "Verbum ex indice exercitationis remotum est.",
    textWeakWord: "Verbum infirmum",
    btnDeleteFromPracticeList: "Ex indice exercitationis delere",
    btnAddToPracticeList: "Ad indicem exercitationis addere",
    btnAddToVocabularyList: "Ad vocabularium personale addere",
    bottomMenuHome: "Domus",
    bottomMenuStudy: "Studium",
    bottomMenuRead: "Lectio",
    bottomMenuSettings: "Optiones",
    btnAddStory: "Fabula addere",
    btnEditStory: "Fabula mutare",
    textTitle: "Titulus",
    textStoryContent: "Continentia fabulae",
    btnSaveAndExit: "Servare et exire",
    overrideWordWarning: "Ingressus verbi iam existens substituetur.",
    textOriginalWord: "Verbum originale",
    textTranslatedWord: "Verbum versum",
    infoAlphaSetToZero: "Alpha ad nullum (0.0) posita est.",
    infoAlphaSetToZeroDotOne: "Alpha ad parvum (0.1) posita est.",
    titleSetAlphaProbability: "Probabilitatem alpha statuere",
    textAlphaProbabilityInfo: "Alpha definit quomodo algorithmus exercitationis verba ad exercendum eligat. Per consuetudinem algorithmus verba cum minore indice doctrinae praeponit (rarius exercitata). Parametrum alpha aliquam probabilitatem addit ut verba cum maximo indice doctrinae quoque eligantur. Si alpha ad nullum ponitur, verba cum maximo indice doctrinae solum apparebunt cum totus index verborum exercitatus erit.",
    textCurrentAlphaProbability: "Probabilitas eligendi verbum in exercitatione praesenti est:",
    btnSetAlphaToZero: "Preme ut alpha ad parvum (0.1) ponas (melius pro magnis indicibus exercitationis; verba cum maximo indice doctrinae parvam tantum probabilitatem habebunt apparendi ne oblivio fiat).",
    btnSetAlphaToZeroDotOne: "Preme ut alpha ad nullum (0.0) ponas (melius pro parvis indicibus exercitationis; omnia verba exercenda sunt donec repetantur).",
    noteOperationCompleted: "Operatio feliciter perfecta est.",
    btnClearWordPracticeList: "Indicem exercitationis verborum purgare?",
    noteClearWordPracticeListWarning: "Haec actio revocari non potest et omnia verba ex indice exercitationis removebit. Verba iterum addere oportebit ad ea exercenda.",
    btnCancel: "Annullare",
    btnOk: "Ita",
    btnSend: "Mittere",
    btnClear: "Purgare",
    btnExit: "Exire",
    btnDelete: "Delere",
    btnContinue: "Pergere",
    btnCheck: "Examinare",
    btnClearVocabulary: "Vocabularium locale purgare?",
    noteClearVocabularyWarning: "Purgatio vocabularii localis omnes versiones in memoria remotas delebit et nexum interretialem requiret cum verbum proxime tangitur ad vertendum. Praeterea verba non memorata modellis AI utentur, quod sumptus additos afferre potest. Vocabularium locale purga si versiones falsas aut insolitas vides.",
    btnClearAppData: "Omnia data applicationis delere?",
    noteClearAppDataWarning: "Purgatio datorum applicationis omnia data localia removebit, inter progressus lectionum, seriem, vocabularium locale, verba didicata, articulos servatos, et alia.",
    titleDataControls: "Moderatio datorum",
    clearVocabulary: "Vocabularium purgare",
    clearAppData: "Data applicationis delere",
    clearWordPracticeList: "Indicem exercitationis verborum purgare",
    exitPracticeSessionAlertTitle: "Ex sessione exercitationis exire?",
    exitPracticeSessionAlertContents: "Omnis progressus in sessione exercitationis praesenti perdetur.",
    debugApiKeySet: "Clavis API feliciter posita est!",
    debugApiKeyUnset: "Clavis API feliciter remota est!",
    modelSetTo: "Modellum positum est ad: ",
    titleAISettings: "Optiones AI",
    debugZone: "Zona debug",
    debugZoneInstruction: "Clavem API pone si vis functiones AI activare. Vacuum relinque ut clavem API removes.",
    debugZoneSetKey: "Clavem API debug ponere",
    debugZoneAPIKey: "Clavis API OpenAI",
    debugZoneTranslationModelSelectorTitle: "Modellum translationis eligere",
    debugZoneTranslationModelSelectorRemark: "Modellum praedefinitum est o4-mini. Comparatum cum modellis o1-mini et o3-mini idem pretium habet, processus translationis fere eodem tempore fit, sed accuratio multo melior est. gpt-4o carius est, minus accuratum, sed celerius quam cetera modella.",
    syncOptionsTitle: "Optiones synchronisationis",
    syncOptionsNotImplemented: "Implementatio systematis Teslasoft ID hanc functionem distulit. Adhuc implendum ...",
    pleaseWait: "Quaeso exspecta ...",
    pleaseWaitSignIn: "Te admittimus ...",
    vocabularyDeleteWordTitle: "Visne hoc verbum ex vocabulario tuo delere?",
    practiceDeleteWordTitle: "Visne hoc verbum ex indice exercitationis delere?",
    actionIrreversible: "Haec actio revocari non potest!",
    vocabularyTitle: "Vocabularium meum",
    practiceWordsTitle: "Exercitatio verborum",
    btnAddWord: "Verbum novum addere",
    hintSearchWords: "Verba quaerere",
    wordsInVocabularyCount: "verbum(a) in vocabulario meo",
    wordsInPracticeListCount: "verbum(a) in indice exercitationis tuo",
    learningIndex: "L.I.",
    emptyVocabulary: "Vocabularium tuum vacuum est. Fabulas lege aut preme bullam 'Verbum novum addere' ut verba ad vocabularium personale addas.",
    emptyPracticeList: "Index exercitationis tuus vacuum est. Verba infirma ex fabulis tuis adde aut preme bullam 'Verbum novum addere' ut verba ad indicem exercitationis personalem addas.",
    startWordPractice: "Exercitationem verborum incipere",
    startWordHardPractice: "Exercitationem difficilem incipere",
    taskTranslateSentence: "Hanc sententiam verte",
    taskTranslateWord: "Hoc verbum verte",
    labelPreviousMistake: "Error prior",
    labelHardExercise: "Exercitatio difficilis",
    answerCorrect: "Recte!",
    answerIncorrect: "Falso!",
    answerIncorrectCorrectText: "Responsum rectum est:",
    demoContentTitle: "Contentum demo (debug)",
    demoStartPracticeSession: "Sessionem exercitationis incipere",
    titlePracticeCompleted: "Exercitatio perfecta est!",
    practiceCompetedCombo: "Series",
    practiceCompetedErrors: "Errores",
    practiceCompetedTime: "Tempus",
    practiceMessageFlawless: "Sine erroribus perfecta! Perge!",
    practiceMessageSomeErrors: "Cum quibusdam erroribus perfecta, sed omnis error gradus ad successum est!",
    deleteStoryTitle: "Visne hanc fabulam delere?",
    telemetrySendError: "Missio datorum telemetriae defecit: ",
    telemetrySent: "Data telemetriae feliciter missa sunt!",
    telemetrySendPrompt: "Visne data telemetriae mittere?",
    telemetrySendDescription: "Data telemetriae continent memoriam vocabularii tui, versionem applicationis, et alias informationes non personales. Mittendo data telemetriae adiuvas ad memoriam globalem aedificandam ut celeritas et accuratio translationis augeantur et sumptus usus AI minuantur.",
    allSettingsSaved: "Omnes optiones servatae sunt.",
    titleError: "Error",
    teslasoftID: "Teslasoft ID",
    teslasoftIDSignedInAs: "Admissus ut ",
    teslasoftIDTapToSignIn: "Tange ad admittendum",
    teslasoftIDTapToSignOut: "Tange ad exeundum",
    teslasoftIDSyncError: "Error synchronisationis",
    pronounceWordsInReaderWhenClicked: "Verba in lectore tacta pronuntiare",
    pronounceWordsInExerciseWhenClicked: "Verba in exercitatione tacta pronuntiare",
    sectionDebugAndExperimental: "Debug et experimentalia",
    usedTTSEngine: "Machina TTS adhibita",
    licensedUnder: "licentiata sub",
    nonCommercialUsageIsPermitted: "Usus non commercialis permittitur.",
    btnSendTelemetry: "Data telemetriae mittere",
    appVersion: "Versio applicationis:",
    appDeveloper: "Auctor:",
    matchWordWithTranslation: "Verbum cum versione sua coniungere",
    titleHowItWorks: "Quomodo operatur?",
    textHowItWorks: "Legentia algorithmum repetitionis distributae utitur ut nova verba efficaciter discas. Cum verbum ad vocabularium personale aut indicem exercitationis addis, applicatio quomodo id verbum noveris ex effectu tuo in exercitationibus aestimat. Verba quibus difficilius uteris saepius in sessionibus exercitationis apparent, verba autem bene nota rarius. Hic modus doctrinae adaptivus efficit ut in verba maxime attentione indigentia incumbas, tempus studii optimizans et retentionem augens. Praeterea haec applicatio permittit fabulas proprias addere, quod processum discendi iucundiorem et contextui magis aptum facit.",
    textIntro: "Salve in Legentia – applicatione ad linguas discendas vi AI instructa, in algorithmo repetitionis distributae fundata.",
}
