/***************************************************************************
 * Copyright (c) 2025-2026 Dmytro Ostapenko. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * *************************************************************************/

export const deDE = {
    appTitle: "Legentia",
    errorAIFeaturesDisabled: "KI-Funktionen sind deaktiviert. Bitte legen Sie zuerst einen API-Schlüssel fest.",
    errorTranslationNotAvailable: "Die Übersetzung ist derzeit nicht verfügbar.",
    voiceModelName: "", // "Latin Male" for latin language
    infoWordAddedToPracticeList: "Wort zur Übungsliste hinzugefügt.",
    infoWordRemovedFromPracticeList: "Wort aus der Übungsliste entfernt.",
    textWeakWord: "Schwaches Wort",
    btnDeleteFromPracticeList: "Aus der Übungsliste löschen",
    btnAddToPracticeList: "Zur Übungsliste hinzufügen",
    btnAddToVocabularyList: "Zum persönlichen Wortschatz hinzufügen",
    bottomMenuHome: "Start",
    bottomMenuStudy: "Lernen",
    bottomMenuRead: "Lesen",
    bottomMenuSettings: "Einstellungen",
    btnAddStory: "Geschichte hinzufügen",
    btnEditStory: "Geschichte bearbeiten",
    textTitle: "Titel",
    textStoryContent: "Inhalt der Geschichte",
    btnSaveAndExit: "Speichern und beenden",
    overrideWordWarning: "Der bestehende Worteintrag wird überschrieben.",
    textOriginalWord: "Originalwort",
    textTranslatedWord: "Übersetztes Wort",
    infoAlphaSetToZero: "Alpha auf Null (0.0) gesetzt.",
    infoAlphaSetToZeroDotOne: "Alpha auf niedrig (0.1) gesetzt.",
    titleSetAlphaProbability: "Alpha-Wahrscheinlichkeit festlegen",
    textAlphaProbabilityInfo: "Alpha definiert, wie der Übungsalgorithmus Wörter zum Üben auswählt. Standardmäßig priorisiert der Algorithmus Wörter mit einem niedrigeren Lernindex (die seltener geübt wurden). Der Alpha-Parameter fügt eine gewisse Wahrscheinlichkeit hinzu, auch Wörter mit dem höchsten Lernindex auszuwählen. Wenn Alpha auf Null gesetzt ist, erscheinen Wörter mit dem höchsten Lernindex erst dann, wenn die gesamte Wortliste geübt wurde.",
    textCurrentAlphaProbability: "Die Wahrscheinlichkeit, dass das Wort in der aktuellen Übung ausgewählt wird, beträgt:",
    btnSetAlphaToZero: "Klicken, um Alpha auf niedrig (0.1) zu setzen (besser für große Übungslisten, Wörter mit maximalem Lernindex haben nur eine geringe Chance, in den Übungen zu erscheinen, um ein Vergessen zu verhindern).",
    btnSetAlphaToZeroDotOne: "Klicken, um Alpha auf Null (0.0) zu setzen (besser für kleine Übungslisten, alle Wörter müssen geübt werden, bis sie sich wiederholen).",
    noteOperationCompleted: "Vorgang erfolgreich abgeschlossen.",
    btnClearWordPracticeList: "Wort-Übungsliste leeren?",
    noteClearWordPracticeListWarning: "Diese Aktion ist nicht rückgängig zu machen und entfernt alle Wörter aus Ihrer Übungsliste. Sie müssen die Wörter erneut hinzufügen, um sie zu üben.",
    btnCancel: "Abbrechen",
    btnOk: "OK",
    btnSend: "Senden",
    btnClear: "Leeren",
    btnExit: "Beenden",
    btnDelete: "Löschen",
    btnContinue: "Weiter",
    btnCheck: "Überprüfen",
    btnClearVocabulary: "Lokalen Wortschatz leeren?",
    noteClearVocabularyWarning: "Das Leeren des lokalen Wortschatzes entfernt alle zwischengespeicherten Übersetzungen und erfordert beim nächsten Antippen eines Wortes eine Internetverbindung. Zusätzlich verwenden nicht zwischengespeicherte Wörter KI-Modelle, was zusätzliche Kosten verursachen kann. Leeren Sie den lokalen Wortschatz, wenn Sie falsche oder ungewöhnliche Übersetzungen sehen.",
    btnClearAppData: "Alle App-Daten löschen?",
    noteClearAppDataWarning: "Das Löschen der App-Daten entfernt alle lokalen Daten, einschließlich Lernfortschritt, Serien, lokalen Wortschatz, gelernte Wörter, gespeicherte Artikel usw.",
    titleDataControls: "Datenverwaltung",
    clearVocabulary: "Wortschatz leeren",
    clearAppData: "App-Daten löschen",
    clearWordPracticeList: "Wort-Übungsliste leeren",
    exitPracticeSessionAlertTitle: "Übungseinheit beenden?",
    exitPracticeSessionAlertContents: "Der gesamte Fortschritt der aktuellen Übungseinheit geht verloren.",
    debugApiKeySet: "API-Schlüssel erfolgreich gesetzt!",
    debugApiKeyUnset: "API-Schlüssel erfolgreich entfernt!",
    modelSetTo: "Modell gesetzt auf: ",
    titleAISettings: "KI-Einstellungen",
    debugZone: "Debug-Bereich",
    debugZoneInstruction: "Legen Sie einen API-Schlüssel fest, um KI-Funktionen zu aktivieren. Leer lassen, um den API-Schlüssel zu entfernen.",
    debugZoneSetKey: "Debug-API-Schlüssel setzen",
    debugZoneAPIKey: "OpenAI API-Schlüssel",
    debugZoneTranslationModelSelectorTitle: "Übersetzungsmodell auswählen",
    debugZoneTranslationModelSelectorRemark: "Das Standardmodell ist o4-mini. Im Vergleich zu den Modellen o1-mini und o3-mini hat es den gleichen Preis, der Übersetzungsprozess dauert ungefähr gleich lange, die Genauigkeit ist jedoch deutlich besser. gpt-4o ist teurer, weniger genau, aber schneller als andere Modelle.",
    syncOptionsTitle: "Synchronisierungsoptionen",
    syncOptionsNotImplemented: "Die Implementierung des Teslasoft-ID-Systems hat die Umsetzung dieser Funktion verzögert. Wird noch implementiert ...",
    pleaseWait: "Bitte warten ...",
    pleaseWaitSignIn: "Sie werden angemeldet ...",
    vocabularyDeleteWordTitle: "Möchten Sie dieses Wort aus Ihrem Wortschatz löschen?",
    practiceDeleteWordTitle: "Möchten Sie dieses Wort aus Ihrer Übungsliste löschen?",
    actionIrreversible: "Diese Aktion ist nicht rückgängig zu machen!",
    vocabularyTitle: "Mein Wortschatz",
    practiceWordsTitle: "Wortübung",
    btnAddWord: "Neues Wort hinzufügen",
    hintSearchWords: "Wörter suchen",
    wordsInVocabularyCount: "Wort/Wörter in meinem Wortschatz",
    wordsInPracticeListCount: "Wort/Wörter in Ihrer Übungsliste",
    learningIndex: "L.I.",
    emptyVocabulary: "Ihr Wortschatz ist leer. Lesen Sie Geschichten oder klicken Sie auf die Schaltfläche „Neues Wort hinzufügen“, um Wörter zu Ihrem persönlichen Wortschatz hinzuzufügen.",
    emptyPracticeList: "Ihre Übungsliste ist leer. Fügen Sie schwache Wörter aus Ihren Geschichten hinzu oder klicken Sie auf die Schaltfläche „Neues Wort hinzufügen“, um Wörter zu Ihrer persönlichen Übungsliste hinzuzufügen.",
    startWordPractice: "Wortübung starten",
    startWordHardPractice: "Schwere Übung starten",
    taskTranslateSentence: "Übersetzen Sie diesen Satz",
    taskTranslateWord: "Übersetzen Sie dieses Wort",
    labelPreviousMistake: "Vorheriger Fehler",
    labelHardExercise: "Schwere Übung",
    answerCorrect: "Richtig!",
    answerIncorrect: "Falsch!",
    answerIncorrectCorrectText: "Die richtige Antwort ist:",
    demoContentTitle: "Demo-Inhalt (Debug)",
    demoStartPracticeSession: "Übungseinheit starten",
    titlePracticeCompleted: "Übung abgeschlossen!",
    practiceCompetedCombo: "Kombination",
    practiceCompetedErrors: "Fehler",
    practiceCompetedTime: "Zeit",
    practiceMessageFlawless: "Ohne Fehler abgeschlossen! Weiter so!",
    practiceMessageSomeErrors: "Mit einigen Fehlern abgeschlossen, aber jeder Fehler ist ein Schritt zum Erfolg!",
    deleteStoryTitle: "Möchten Sie diese Geschichte löschen?",
    telemetrySendError: "Senden der Telemetriedaten fehlgeschlagen: ",
    telemetrySent: "Telemetriedaten erfolgreich gesendet!",
    telemetrySendPrompt: "Möchten Sie Telemetriedaten senden?",
    telemetrySendDescription: "Telemetriedaten enthalten Ihren Wortschatz-Cache, die Anwendungsversion und andere nicht-personenbezogene Informationen. Durch das Senden von Telemetriedaten helfen Sie beim Aufbau eines globalen Caches, um die Übersetzungsgeschwindigkeit und -genauigkeit zu erhöhen und die Kosten für die Nutzung von KI zu reduzieren.",
    allSettingsSaved: "Alle Einstellungen gespeichert.",
    titleError: "Fehler",
    teslasoftID: "Teslasoft-ID",
    teslasoftIDSignedInAs: "Angemeldet als ",
    teslasoftIDTapToSignIn: "Antippen zum Anmelden",
    teslasoftIDTapToSignOut: "Antippen zum Abmelden",
    teslasoftIDSyncError: "Synchronisierungsfehler",
    pronounceWordsInReaderWhenClicked: "Wörter im Lesemodus beim Antippen aussprechen",
    pronounceWordsInExerciseWhenClicked: "Wörter in Übungen beim Antippen aussprechen",
    sectionDebugAndExperimental: "Debug und experimentell",
    usedTTSEngine: "Verwendete TTS-Engine",
    licensedUnder: "lizenziert unter",
    nonCommercialUsageIsPermitted: "Nicht-kommerzielle Nutzung ist erlaubt.",
    btnSendTelemetry: "Telemetriedaten senden",
    appVersion: "App-Version:",
    appDeveloper: "Entwickler:",
    matchWordWithTranslation: "Ordnen Sie das Wort seiner Übersetzung zu",
    titleHowItWorks: "Wie funktioniert es?",
    textHowItWorks: "Legentia verwendet einen Algorithmus zur verteilten Wiederholung, um Ihnen zu helfen, neue Wörter effektiv zu lernen. Wenn Sie ein Wort zu Ihrem persönlichen Wortschatz oder Ihrer Übungsliste hinzufügen, verfolgt die App, wie gut Sie dieses Wort anhand Ihrer Leistung in den Übungen kennen. Wörter, mit denen Sie Schwierigkeiten haben, erscheinen häufiger in Übungseinheiten, während Wörter, die Sie gut kennen, seltener erscheinen. Dieser adaptive Lernansatz stellt sicher, dass Sie sich auf die Wörter konzentrieren, die die meiste Aufmerksamkeit benötigen, optimiert Ihre Lernzeit und verbessert die Behaltensleistung. Zusätzlich ermöglicht diese App das Hinzufügen eigener Geschichten, wodurch der Lernprozess ansprechender und kontextuell relevanter wird.",
    textIntro: "Willkommen bei Legentia – einer KI-gestützten Sprachlern-App basierend auf dem Algorithmus der verteilten Wiederholung.",
}
