/***************************************************************************
 * Copyright (c) 2025-2026 Dmytro Ostapenko. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * *************************************************************************/

export const enUS = {
    appTitle: "Legentia",
    errorAIFeaturesDisabled: "AI features are disabled. Please set an API key first.",
    errorTranslationNotAvailable: "Translation is not available right now.",
    voiceModelName: "", // "Latin Male" for latin language
    infoWordAddedToPracticeList: "Word added to practice list.",
    infoWordRemovedFromPracticeList: "Word removed from practice list.",
    textWeakWord: "Weak word",
    btnDeleteFromPracticeList: "Delete from practice list",
    btnAddToPracticeList: "Add to practice list",
    btnAddToVocabularyList: "Add to personal vocabulary",
    bottomMenuHome: "Home",
    bottomMenuStudy: "Study",
    bottomMenuRead: "Read",
    bottomMenuSettings: "Settings",
    btnAddStory: "Add story",
    btnEditStory: "Edit story",
    textTitle: "Title",
    textStoryContent: "Story content",
    btnSaveAndExit: "Save and exit",
    overrideWordWarning: "Existing word entry will be overridden.",
    textOriginalWord: "Original word",
    textEnglishWord: "English word",
    infoAlphaSetToZero: "Alpha set to zero (0.0).",
    infoAlphaSetToZeroDotOne: "Alpha set to low (0.1).",
    titleSetAlphaProbability: "Set alpha probability",
    textAlphaProbabilityInfo: "Alpha defines how exercise algorithm will select words for practising. By default, words selection algorithm prioritizes words that have the less learning index (have been practised less times). Alpha parameter adds some chance to select words with the maximum learning index. If alpha is set to zero, then words with the maximum learning index will appear only when the whole words list has been practised.",
    textCurrentAlphaProbability: "The probability of selecting the word in the current exercise is:",
    btnSetAlphaToZero: "Click to set alpha to low (0.1) (better for large word practice lists, words with max learning index will have small chance of appearing in the exercises to prevent user from forgetting it).",
    btnSetAlphaToZeroDotOne: "Click to set alpha to zero (0.0) (better for small word practice lists, all words must be practised until it will repeat).",
    noteOperationCompleted: "Operation completed successfully.",
    btnClearWordPracticeList: "Clear word practice list?",
    noteClearWordPracticeListWarning: "This action is irreversible and will remove all words from your practice list. You will need to add words again to practice them.",
    btnCancel: "Cancel",
    btnOk: "Ok",
    btnSend: "Send",
    btnClear: "Clear",
    btnExit: "Exit",
    btnDelete: "Delete",
    btnContinue: "Continue",
    btnCheck: "Check",
    btnClearVocabulary: "Clear local vocabulary?",
    noteClearVocabularyWarning: "Clearing local vocabulary will removed all cached translations and will require Internet connection next time you tap the word to translate it. Additionally, uncached words will use AI models which may incur additional charges. Clear local vocabulary if you see incorrect or unusual translations.",
    btnClearAppData: "Clear all app data?",
    noteClearAppDataWarning: "Clearing app data will remove all local data, including lesson progresses, streak, local vocabulary, learned words, saved articles, etc.",
    titleDataControls: "Data controls",
    clearVocabulary: "Clear vocabulary",
    clearAppData: "Clear app data",
    clearWordPracticeList: "Clear word practice list",
    exitPracticeSessionAlertTitle: "Exit practice session?",
    exitPracticeSessionAlertContents: "All progress in the current practice session will be lost.",
    debugApiKeySet: "API key set successfully!",
    debugApiKeyUnset: "API key unset successfully!",
    modelSetTo: "Model set to: ",
    titleAISettings: "AI Settings",
    debugZone: "Debug zone",
    debugZoneInstruction: "Set API key if you want to enable AI features. Leave blank to unset an API key.",
    debugZoneSetKey: "Set debug API key",
    debugZoneAPIKey: "OpenAI API key",
    debugZoneTranslationModelSelectorTitle: "Select translation model",
    debugZoneTranslationModelSelectorRemark: "Default model is o4-mini. Comparing to the models o1-mini and o3-mini it has the same price, translation process takes appropriately the same amount of time, but the accuracy id much better. gpt-4o is more expensive, less accurate, but is the faster than other models.",
    syncOptionsTitle: "Sync options",
    syncOptionsNotImplemented: "Implementation of Teslasoft ID system has postponed the implementation of this feature. To be implemented ...",
    pleaseWait: "Please wait ...",
    pleaseWaitSignIn: "We are signing you in ...",
    vocabularyDeleteWordTitle: "Would you like to delete this word from your vocabulary?",
    practiceDeleteWordTitle: "Would you like to delete this word from your practice list?",
    actionIrreversible: "This action is irreversible!",
    vocabularyTitle: "My vocabulary",
    practiceWordsTitle: "Word practice",
    btnAddWord: "Add new word",
    hintSearchWords: "Search words",
    wordsInVocabularyCount: "word(s) in my vocabulary",
    wordsInPracticeListCount: "word(s) in your practice list",
    learningIndex: "L.I.",
    emptyVocabulary: "Your vocabulary is empty. Read stories or click the 'Add new word' button to add words to your personal vocabulary.",
    emptyPracticeList: "Your practice list is empty. Add weak words from your stories or click the 'Add new word' button to add words to your personal practice list.",
    startWordPractice: "Start word practice",
    startWordHardPractice: "Start hard exercise",
    taskTranslateSentence: "Translate this sentence",
    taskTranslateWord: "Translate this word",
    labelPreviousMistake: "Previous mistake",
    labelHardExercise: "Hard exercise",
    answerCorrect: "Correct!",
    answerIncorrect: "Incorrect!",
    answerIncorrectCorrectText: "Correct answer is:",
    demoContentTitle: "Demo content (debug)",
    demoStartPracticeSession: "Start practice session",
    titlePracticeCompleted: "Practice completed!",
    practiceCompetedCombo: "Combo",
    practiceCompetedErrors: "Errors",
    practiceCompetedTime: "Time",
    practiceMessageFlawless: "Finished with no mistakes! Keep going!",
    practiceMessageSomeErrors: "Finished with some mistakes, but every mistake is a step to success!",
    deleteStoryTitle: "Would you like to delete this story?",
    telemetrySendError: "Failed to send telemetry data: ",
    telemetrySent: "Telemetry sent successfully!",
    telemetrySendPrompt: "Would you like to send telemetry data?",
    telemetrySendDescription: "Telemetry data includes your vocabulary cache, application version, and other non-personal information. By sending telemetry data, you will help to build global cache to increase translation speed and accuracy and reduce costs related to the usage of AI.",
    allSettingsSaved: "All settings saved.",
    titleError: "Error",
    teslasoftID: "Teslasoft ID",
    teslasoftIDSignedInAs: "Signed in as ",
    teslasoftIDTapToSignIn: "Tap to sign in",
    teslasoftIDTapToSignOut: "Tap to sign out",
    teslasoftIDSyncError: "Sync error",
    pronounceWordsInReaderWhenClicked: "Pronounce words in reader when clicked",
    pronounceWordsInExerciseWhenClicked: "Pronounce words in exercise when clicked",
    sectionDebugAndExperimental: "Debug and experimental",
    usedTTSEngine: "Used TTS engine",
    licensedUnder: "licensed under",
    nonCommercialUsageIsPermitted: "Non-commercial usage is permitted.",
    btnSendTelemetry: "Send telemetry data",
    appVersion: "App version:",
    appDeveloper: "Developer:",
    matchWordWithTranslation: "Match the word with its translation",
    titleHowItWorks: "How it works?",
    textHowItWorks: "Legentia uses spaced repetition algorithm to help you learn new words effectively. When you add a word to your personal vocabulary or practice list, the app tracks how well you know that word based on your performance in exercises. Words that you struggle with will appear more frequently in practice sessions, while words you know well will appear less often. This adaptive learning approach ensures that you focus on the words that need the most attention, optimizing your study time and improving retention. Additionally, this app allows you to add custom stories, making the learning process more engaging and contextually relevant.",
    textIntro: "Welcome to Legentia - AI-powered language learning app based on spacing repetition algorithm.",

}
